### ISSUE TITLE
US_regional.sqlite seems to require password

### ISSUE THREAD

**Issue by jkiviluo** [TemoaProject/oeo#8]
First attempt (with older version of DB Browser for SQLite)
- Downloaded US_regional.sqlite from commit d34e818
- Tried to open with DB Browser for SQLite
- Asks for a password (SQLCipher encryption -- please enter the key used to encrypt the database)
- I don't have a password...

Second attempt (with latest version of DB Browser for SQLite --> 3.12.1)
- Downloaded US_regional.sqlite from commit d34e818
- Tried to open with DB Browser for SQLite
- Complains: "Could not open a database file. Reason: file is not a database file"

**Comment by TemoaProject** [comment]
I suspect you may be trying to open the sql text file rather than the binary sqlite file. I am able to download and open US_Regional.sqlite on my machine without a problem using DB Browser for SQLite 3.12.0. When I try to open the sql file in DB Browser for SQLite, I first get prompted for a password and an then told that the file is invalid.

**Comment by jkiviluo** [comment]
Yes, my bad. I had an US_Regional.sqlite file that was 11 kB of size (the same as the US_Regional.sql). Somehow the name had gotten mangled.
